---
title: "Alumni"
---

::: {.section-block}

::: {.intro-text}
Former members of the Macroevolution & Macroecology Group
:::

:::

::: {.section-block}

::: {.alumni-section}

### Former postdocs

- Keaghan Yaxley (postdoctoral RA, 2022–2024)
- Andrew Ritchie (postdoctoral RA, 2019–2021)
- Russell Dinnage (postdoctoral RA, 2015–2019)
- Caroline Chong (postdoctoral RA, 2015)
- Dan Warren (postdoctoral RA, 2012–2014)
- Peter Cowman (postdoctoral RA, 2012–2014)
- Haris Saslis-Lagoudakis (postdoctoral RA, 2013–2014)
- Rob Lanfear (postdoctoral RA, 2008–2012)
- Renae Pratt (postdoctoral RA, 2010–2011)
- Simon Ho (ARC postdoctoral fellow, 2008–2010)
- Matthew Phillips (ARC postdoctoral fellow, 2007–2009)

:::

:::

::: {.section-block}

::: {.alumni-section}

### Former PhD students

- Alex Skeels (PhD 2020, *The Ecological and Evolutionary Drivers of Spatial Biodiversity Patterns*)
- Zoe Reynolds (PhD 2019, *Disturbed birds: The function of fire in shaping patterns of avian diversity in south-eastern Australia*)
- David Duchene (PhD 2016, *The importance of phylogenetic model assessment for macroevolutionary inference*)
- Camile Moray (PhD 2015, *Evolutionary patterns of salt tolerance in angiosperms*)
- Emily Hanna (PhD 2014, *Drivers of mammalian extinction and decline*)
- Rob Lanfear (PhD 2007, *The evolution of animal body plans*)
- Jessica Thomas (PhD 2008, *The tempo and mode of invertebrate molecular evolution*)
- Eric Fontanillas (PhD 2009, *Molecular evolution in Metazoa: causes and consequences of variation in rate of molecular evolution*)

:::

:::

::: {.section-block}

::: {.alumni-section}

### Former honours/masters students

- Mina Kearns (Honours 2023–24, *Spatial Variability of Phylogenetic Diversity: Implications for Conservation Area Planning*)
- Zachary Trafford (Honours 2023)
- Kathryn MacPherson (Masters 2023, *How den characteristics can be used to predict habitat suitability for an endangered marsupial*)
- Emmeline Norris (Honours 2022–23, *Alternative conservation options for native mammals in the Australian Monsoonal Tropics*)
- Rhiannon Schembri (Honours 2021, *Molecular evolution and speciation in the Australian Eugongylus skink clade*)
- Felix Smits (Honours 2020–21, *Drivers of Extinction Risk and Spatial Conservation Prioritization in Australian mammals*)
- Jarrod Sopniewski (Honours 2020, *The future of frogs: Modelling threats to Australian frogs in the face of climate change*)
- Oliver Webeck (Honours 2019, *Projecting geographic distributions of Hakea (Proteaceae) under climate change*)
- Isaac Bell (Honours 2019, *Explaining variation in extinction risk and predicting future decline in birds*)
- Ellen Miech (Honours 2016, *Identifying drivers of Proteaceae declines on Western Australia's islands*)
- Keaghan Yaxley (Honours 2015–16, *Conserving branch lengths: Phylogenetic diversity and molecular evolution*)
- Alex Skeels (Honours 2015, *Niche evolution and spatial diversity patterns in Mediterranean hotspot plant genera*)
- Caela Welsh (Honours 2015, *The influence of population size on rates of language evolution*)
- Emma Day (Honours 2014–15, *Is specialization an evolutionary dead-end?*)
- William McAlister (Honours 2014–15, *Investigating the artefactual relationship between niche breadth and geographic range size*)
- Christiana McDonald-Spicer (Honours 2014–15, *Where are the global diversity hotspots of the Daisy family (Asteraceae)?*)
- Zoe Reynolds (Honours 2012, *Phylogenetic, taxonomic, and functional turnover among Proteaceae assemblages*)
- Emily Hanna (Honours 2009, *Modelling extinction risk using multiple model averaging: a case study with Australian mammals*)
- Tom Bennett (Honours 2010, *Evolution of salt tolerance in grasses*)

:::

:::

::: {.section-block}

::: {.alumni-section}

### Former research assistants

- Jessica Fenker Antunes
- Zoe Reynolds
- Renae Pratt
- Tom Bennett
- Gillian Gibb

:::

:::

::: {.section-block}

::: {.alumni-section}

### Former visiting students

- Flavia Machado (graduate internship, 2017)
- Ignacio Morales Castilla (graduate internship, 2011)

:::

:::
